# This file is machine-generated - editing it directly is not advised

[[FastLapackInterface]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "880880be3a63b04f7988612732f3d062b381c4d2"
uuid = "29a986be-02c6-4525-aec4-84b980013641"
version = "0.1.1"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[PolynomialMatrixEquations]]
deps = ["FastLapackInterface", "LinearAlgebra"]
git-tree-sha1 = "8ad93e837431f712285e87ff0197b8be35a97dcd"
uuid = "4f9d485d-518f-41ed-81c8-372cd804c93b"
version = "0.1.0"
